export const TODO_LIST = "TODO_LIST"
export const ADD_TODO = "ADD_TODO"
export const EDIT_TODO = "EDIT_TODO"
export const ADD_BELOW_TODO = "ADD_BELOW_TODO"
export const EDIT_BELOW_TODO = "EDIT_BELOW_TODO"
export const DELETE_TODO = "DELETE_TODO"
